export interface NutritionDetails {
    ala_fatty_acid: number;
    alanine: number;
    alcohol: number;
    alpha_carotene: number;
    arginine: number;
    aspartic_acid: number;
    beta_carotene: number;
    betaine: number;
    caffeine: number;
    calcium: number;
    calories: number;
    carbs: number;
    cholesterol: number;
    choline: number;
    copper: number;
    cystine: number;
    dha_fatty_acid: number;
    dpa_fatty_acid: number;
    epa_fatty_acid: number;
    fats: number;
    fiber: number;
    fluoride: number;
    folate: number;
    fructose: number;
    fruit_servings: number;
    galactose: number;
    glucose: number;
    glutamic_acid: number;
    glycine: number;
    histidine: number;
    hydroxyproline: number;
    iron: number;
    isoleucine: number;
    lactose: number;
    leucine: number;
    lycopene: number;
    lysine: number;
    magnesium: number;
    maltose: number;
    manganese: number;
    methionine: number;
    monounsaturated_fats: number;
    niacin: number;
    pantothenic_acid: number;
    phenylalanine: number;
    phosphorus: number;
    polyunsaturated_fats: number;
    potassium: number;
    price: number;
    proline: number;
    proteins: number;
    retinol: number;
    riboflavin: number;
    saturated_fats: number;
    selenium: number;
    serine: number;
    sodium: number;
    starch: number;
    sucrose: number;
    sugar: number;
    theobromine: number;
    thiamine: number;
    threonine: number;
    total_omega_3: number;
    total_omega_6: number;
    trans_fats: number;
    tryptophan: number;
    tyrosine: number;
    valine: number;
    veggie_servings: number;
    vit_a: number;
    vit_a_iu: number;
    vit_b12: number;
    vit_b6: number;
    vit_c: number;
    vit_d: number;
    vit_d2: number;
    vit_d3: number;
    vit_d_iu: number;
    vit_e: number;
    vit_k: number;
    water: number;
    zinc: number;
}

export interface DetailedFoodNutritionDetails {
    id: number;
    theobromine?: number | null;
    sucrose?: number | null;
    vit_a_iu?: number | null;
    vit_d_iu?: number | null;
    starch?: number | null;
    alpha_carotene?: number | null;
    beta_carotene?: number | null;
    pantothenic_acid?: number | null;
    ala_fatty_acid?: number | null;
    dha_fatty_acid?: number | null;
    epa_fatty_acid?: number | null;
    dpa_fatty_acid?: number | null;
    total_omega_3?: number | null;
    total_omega_6?: number | null;
    serving_vit_a_iu?: number | null;
    serving_vit_d_iu?: number | null;
    serving_starch?: number | null;
    serving_alpha_carotene?: number | null;
    serving_beta_carotene?: number | null;
    serving_pantothenic_acid?: number | null;
    serving_ala_fatty_acid?: number | null;
    serving_dha_fatty_acid?: number | null;
    serving_epa_fatty_acid?: number | null;
    serving_dpa_fatty_acid?: number | null;
    serving_total_omega_3?: number | null;
    serving_total_omega_6?: number | null;
    per_200_cal_theobromine?: number | null;
    per_200_cal_sucrose?: number | null;
    per_200_cal_vit_a_iu?: number | null;
    per_200_cal_vit_d_iu?: number | null;
    per_200_cal_starch?: number | null;
    per_200_cal_alpha_carotene?: number | null;
    per_200_cal_beta_carotene?: number | null;
    per_200_cal_pantothenic_acid?: number | null;
    per_200_cal_ala_fatty_acid?: number | null;
    per_200_cal_dha_fatty_acid?: number | null;
    per_200_cal_epa_fatty_acid?: number | null;
    per_200_cal_dpa_fatty_acid?: number | null;
    per_200_cal_total_omega_3?: number | null;
    per_200_cal_total_omega_6?: number | null;
    calories?: number | null;
    carbs?: number | null;
    fats?: number | null;
    proteins?: number | null;
    caffeine?: number | null;
    price?: number | null;
    fiber?: number | null;
    sugar?: number | null;
    calcium?: number | null;
    iron?: number | null;
    magnesium?: number | null;
    phosphorus?: number | null;
    potassium?: number | null;
    sodium?: number | null;
    zinc?: number | null;
    copper?: number | null;
    fluoride?: number | null;
    manganese?: number | null;
    selenium?: number | null;
    vit_a?: number | null;
    vit_b6?: number | null;
    vit_b12?: number | null;
    vit_c?: number | null;
    vit_d?: number | null;
    vit_d2?: number | null;
    vit_d3?: number | null;
    vit_e?: number | null;
    vit_k?: number | null;
    retinol?: number | null;
    lycopene?: number | null;
    thiamine?: number | null;
    riboflavin?: number | null;
    niacin?: number | null;
    folate?: number | null;
    choline?: number | null;
    cholesterol?: number | null;
    betaine?: number | null;
    glucose?: number | null;
    fructose?: number | null;
    lactose?: number | null;
    maltose?: number | null;
    galactose?: number | null;
    alcohol?: number | null;
    tryptophan?: number | null;
    threonine?: number | null;
    isoleucine?: number | null;
    leucine?: number | null;
    lysine?: number | null;
    methionine?: number | null;
    cystine?: number | null;
    phenylalanine?: number | null;
    tyrosine?: number | null;
    valine?: number | null;
    arginine?: number | null;
    histidine?: number | null;
    alanine?: number | null;
    aspartic_acid?: number | null;
    glutamic_acid?: number | null;
    glycine?: number | null;
    proline?: number | null;
    serine?: number | null;
    hydroxyproline?: number | null;
    trans_fats?: number | null;
    saturated_fats?: number | null;
    monounsaturated_fats?: number | null;
    polyunsaturated_fats?: number | null;
    serving_carbs?: number | null;
    serving_fats?: number | null;
    serving_proteins?: number | null;
    serving_calories?: number | null;
    serving_price?: number | null;
    serving_caffeine?: number | null;
    serving_theobromine?: number | null;
    serving_fiber?: number | null;
    serving_calcium?: number | null;
    serving_iron?: number | null;
    serving_magnesium?: number | null;
    serving_phosphorus?: number | null;
    serving_potassium?: number | null;
    serving_sodium?: number | null;
    serving_zinc?: number | null;
    serving_copper?: number | null;
    serving_fluoride?: number | null;
    serving_manganese?: number | null;
    serving_selenium?: number | null;
    serving_vit_a?: number | null;
    serving_vit_b6?: number | null;
    serving_vit_b12?: number | null;
    serving_vit_c?: number | null;
    serving_vit_d?: number | null;
    serving_vit_d2?: number | null;
    serving_vit_d3?: number | null;
    serving_vit_e?: number | null;
    serving_vit_k?: number | null;
    serving_retinol?: number | null;
    serving_lycopene?: number | null;
    serving_thiamine?: number | null;
    serving_riboflavin?: number | null;
    serving_niacin?: number | null;
    serving_folate?: number | null;
    serving_choline?: number | null;
    serving_cholesterol?: number | null;
    serving_betaine?: number | null;
    serving_glucose?: number | null;
    serving_fructose?: number | null;
    serving_lactose?: number | null;
    serving_maltose?: number | null;
    serving_galactose?: number | null;
    serving_sucrose?: number | null;
    serving_sugar?: number | null;
    serving_alcohol?: number | null;
    serving_tryptophan?: number | null;
    serving_threonine?: number | null;
    serving_isoleucine?: number | null;
    serving_leucine?: number | null;
    serving_lysine?: number | null;
    serving_methionine?: number | null;
    serving_cystine?: number | null;
    serving_phenylalanine?: number | null;
    serving_tyrosine?: number | null;
    serving_valine?: number | null;
    serving_arginine?: number | null;
    serving_histidine?: number | null;
    serving_alanine?: number | null;
    serving_aspartic_acid?: number | null;
    serving_glutamic_acid?: number | null;
    serving_glycine?: number | null;
    serving_proline?: number | null;
    serving_serine?: number | null;
    serving_hydroxyproline?: number | null;
    serving_trans_fats?: number | null;
    serving_saturated_fats?: number | null;
    serving_monounsaturated_fats?: number | null;
    serving_polyunsaturated_fats?: number | null;
    per_200_cal_calories?: number | null;
    per_200_cal_carbs?: number | null;
    per_200_cal_fats?: number | null;
    per_200_cal_proteins?: number | null;
    per_200_cal_caffeine?: number | null;
    per_200_cal_price?: number | null;
    per_200_cal_fiber?: number | null;
    per_200_cal_sugar?: number | null;
    per_200_cal_calcium?: number | null;
    per_200_cal_iron?: number | null;
    per_200_cal_magnesium?: number | null;
    per_200_cal_phosphorus?: number | null;
    per_200_cal_potassium?: number | null;
    per_200_cal_sodium?: number | null;
    per_200_cal_zinc?: number | null;
    per_200_cal_copper?: number | null;
    per_200_cal_fluoride?: number | null;
    per_200_cal_manganese?: number | null;
    per_200_cal_selenium?: number | null;
    per_200_cal_vit_a?: number | null;
    per_200_cal_vit_b6?: number | null;
    per_200_cal_vit_b12?: number | null;
    per_200_cal_vit_c?: number | null;
    per_200_cal_vit_d?: number | null;
    per_200_cal_vit_d2?: number | null;
    per_200_cal_vit_d3?: number | null;
    per_200_cal_vit_e?: number | null;
    per_200_cal_vit_k?: number | null;
    per_200_cal_retinol?: number | null;
    per_200_cal_lycopene?: number | null;
    per_200_cal_thiamine?: number | null;
    per_200_cal_riboflavin?: number | null;
    per_200_cal_niacin?: number | null;
    per_200_cal_folate?: number | null;
    per_200_cal_choline?: number | null;
    per_200_cal_cholesterol?: number | null;
    per_200_cal_betaine?: number | null;
    per_200_cal_glucose?: number | null;
    per_200_cal_fructose?: number | null;
    per_200_cal_lactose?: number | null;
    per_200_cal_maltose?: number | null;
    per_200_cal_galactose?: number | null;
    per_200_cal_alcohol?: number | null;
    per_200_cal_tryptophan?: number | null;
    per_200_cal_threonine?: number | null;
    per_200_cal_isoleucine?: number | null;
    per_200_cal_leucine?: number | null;
    per_200_cal_lysine?: number | null;
    per_200_cal_methionine?: number | null;
    per_200_cal_cystine?: number | null;
    per_200_cal_phenylalanine?: number | null;
    per_200_cal_tyrosine?: number | null;
    per_200_cal_valine?: number | null;
    per_200_cal_arginine?: number | null;
    per_200_cal_histidine?: number | null;
    per_200_cal_alanine?: number | null;
    per_200_cal_aspartic_acid?: number | null;
    per_200_cal_glutamic_acid?: number | null;
    per_200_cal_glycine?: number | null;
    per_200_cal_proline?: number | null;
    per_200_cal_serine?: number | null;
    per_200_cal_hydroxyproline?: number | null;
    per_200_cal_trans_fats?: number | null;
    per_200_cal_saturated_fats?: number | null;
    per_200_cal_monounsaturated_fats?: number | null;
    per_200_cal_polyunsaturated_fats?: number | null;
}
